dist: xenial
language: python
python:
  - "3.6"
env:
  CPLUS_INCLUDE_PATH=/usr/include/gdal
  C_INCLUDE_PATH=/usr/include/gdal
before_install:
# The version installed by default of libgdal is ancient
# add the ubuntugis repo to update to a more recent version
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install libgdal-dev -y
install:
  - pip install -e .
  - pip install gdal==`gdal-config --version`
# command to run tests
script:
  - cd tests
  - ./test_main.sh