language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install libgdal-dev
install:
  - pip install -e .
  - pip install -r test.txt
# command to run tests
script:
  - tests/test_main.sh